## K-Link Search Javascript library Continuous Integration script

stages:
  - test
  - build
  - release

cache:
  key: "klinksearchjs"
  paths:
  - .yarn

## Execute the Unit tests to confirm that at least 
## something is working
test:
  image: node:8
  stage: test
  before_script:
    - yarn config set cache-folder .yarn
    - yarn
    - yarn test
  script:
   - npm run test
  tags:
    - docker

## Generates the production optimized build starting from the development
## build already available in the repository
build_for_release:
  image: node:8
  stage: build
  before_script:
    - yarn config set cache-folder .yarn
    - yarn
  script:
    - yarn production
  tags:
    - docker
  artifacts:
    expire_in: 1 week
    paths:
    - dist/js
    - dist/css
  only:
    - tags

